LICENSE, package.json
1. Add  Lisence file
2. push to public repo
=> DOPS-1308  Make build of soramitsu-js-ui-library public

package.json, src/components/Table/SHierarchicalTable.vue, src/components/Table/STable.vue, src/components/Table/STableColumn.vue, src/components/Table/index.ts, src/components/index.ts, src/index.ts, src/stories/Table/SHierarchicalTable.stories.ts, src/styles/table.scss, src/types/components.ts
https://soramitsu.atlassian.net/browse/UNK-589
=> UNK-659 Implement hierarchical table

src/styles/select.scss
https://soramitsu.atlassian.net/browse/UNK-659
=> UNK-659 Remove the white layer that overlaps the arrow in the select

package.json, src/components/Pagination/SPagination.vue, src/components/Table/SHierarchicalTable.vue
https://soramitsu.atlassian.net/browse/UNK-752
=> UNK-752 Add per page text parameter to pagination

package.json, src/components/Input/SJsonInput.vue, src/components/Tooltip/STooltip.vue
https://soramitsu.atlassian.net/browse/UNK-722
=> UNK-722 Change tooltip disappearance delay

src/components/Input/SJsonInput.vue, src/styles/json-input.scss
https://soramitsu.atlassian.net/browse/UNK-591
=> UNK-591 Add the ability to expand the JSON editor component by pulling the slider in the corner of the field

package.json, src/styles/form.scss, src/styles/input.scss
* fix: input & textarea error style
* fix: "placeholder" error color
* fix: handle autofill case
* build: up version to 0.9.7
=> Release 0.9.7

package.json, src/styles/input.scss
=> fix: set fixed `SInput` height instead of `min-height`

src/components/Input/SJsonInput.vue
https://soramitsu.atlassian.net/browse/UNK-591
=> UNK-591 Fix jsoneditor resize

src/components/Input/SInput/SInput.vue
https://soramitsu.atlassian.net/browse/UNK-884
=> UNK-884 Fix file input on click

src/styles/select.scss
I've fixed the problem with the display of the select component arrow
=> Fix select arrow icon

src/styles/neumorphism/input.scss, src/styles/variables.scss
[PW-239]: Bridge Design Update
* Neumorphism: Updated input placeholder color.
* Neumorphism: Updated shadow for cards and dialogs.
[PW-239]: https://soramitsu.atlassian.net/browse/PW-239
=> PW-239: Bridge Design Update

package.json, src/styles/icons.scss
=> Dark Theme: Icons Color Update

src/components/Divider/consts.ts, src/styles/divider.scss
* Added tertiary SDivider type.
=> SDivider: Tertiary Type

package.json, src/components/Tab/STabs/STabs.vue, src/styles/neumorphism/tabs.scss
* Neu Tabs Card: Added Card Tabs Type.
=> Neu Tabs Card Type

Jenkinsfile
[Duty] 27.12.21.
1. Update CI config.
Signed-off-by: Dmitriy Creed <creed@soramitsu.co.jp>
=> [Duty] Update CI config

packages/ui/cypress/component/SPopover.spec.cy.ts, packages/ui/cypress/component/SSelect.spec.cy.ts, packages/ui/cypress/tsconfig.json, packages/ui/etc/api/ui.api.md, packages/ui/package.json, packages/ui/src/components/Modal/util.ts, packages/ui/src/components/Popover/SPopover.ts, packages/ui/src/components/Popover/SPopoverWrappedTransition.vue, packages/ui/src/components/Popover/api.ts, packages/ui/src/components/Popover/index.ts, packages/ui/src/components/Popover/util.ts, packages/ui/src/components/Select/SSelectBase.vue, packages/ui/src/composables/popper.ts, packages/ui/src/lib.ts, packages/ui/stories/Popover.stories.scss, packages/ui/stories/Popover.stories.ts, packages/ui/stories/tsconfig.json, packages/ui/windi.config.ts, yarn.lock
It is mostly functional than design-system component. It may be called a higher-order Vue 3 wrapper over `@popperjs/core` library.
Out of the box features:
- Placement, distance, skidding reactive control
- `hover`, `click` or `manual` trigger types
- Click-outside handle for `click` trigger; emits `click-outside` event despite of a trigger type
- Show/hide delays - works with any trigger
- Seamless elements bindings
It is easy to extend its functionality with more features.
**Basic example:**
```vue
<template>
<SPopover
placement="top-start"
distance="4"
hide-delay="300"
show-delay="100"
>
<template #trigger>
<button>Hover me</button>
</template>
<template #popper="{ show }">
<span v-if="show"> Voila! </span>
</template>
</SPopover>
</template>
```
**Manual mode:**
```vue
<template> …
```
=> WDS-65 - Popover component

package.json, src/components/Tooltip/STooltip.vue
https://soramitsu.atlassian.net/browse/UNK-1007
=> UNK-1007 Button tip pops up after tab switching

packages/ui/cypress/component/SSpinner.spec.cy.ts, packages/ui/src/components/Spinner/SSpinner.vue
=> fix: use `Number()` instead of `parseFloat()`

Dockerfile
[DOPS-1632]: Review all Sora2 project related dockerfiles
1. Change image to nginxinc/nginx-unprivileged:1.20 (official)
Signed-off-by: Nikita Zaporozhets <zaporozhets@soramitsu.co.jp>
[DOPS-1632]: https://soramitsu.atlassian.net/browse/DOPS-1632
=> [DOPS-1632] Review all Sora2 project related dockerfiles 

.changeset/heavy-oranges-sparkle.md, packages/ui/src/lib.ts
Added generated windicss reset and atom styles to bundle
=> fix(ui): add generated styles to bundle

package.json, src/styles/neumorphism/tooltip.scss
[PW-650]: Refactor Tooltips/Notifications For Copy Address Operation
* STooltip: Added center alignment for the arrow.
[PW-650]: https://soramitsu.atlassian.net/browse/PW-650
=> PW-650: Refactor Tooltips/Notifications For Copy Address Operation

.changeset/eleven-shrimps-press.md, packages/ui/package.json, packages/ui/test/after-build/.gitignore, packages/ui/test/after-build/esm-tree-shaking-test-lib/proxy.ts, packages/ui/test/after-build/test.ts, packages/ui/vite.config.ts
More about the problem: https://v3.nuxtjs.org/guide/going-further/esm/#what-kinds-of-problems-can-there-be
Solution: https://v3.nuxtjs.org/guide/going-further/esm/#what-are-valid-imports-in-a-nodejs-context
=> Fix CJS & MJS imports

package.json, src/components/Icon/consts.ts, src/styles/icons.scss
[PW-734]: Fix "received" word translations and keys
* Fixed Receive Misspelling
[PW-734]: https://soramitsu.atlassian.net/browse/PW-734
=> PW-734: Fix "received" word translations and keys

Jenkinsfile
[DOPS-1857] Add publish button for all libraries PRs & branches in Jenkins
Add "publish" button for all libraries PRs & branches in Jenkins
[DOPS-1857]: https://soramitsu.atlassian.net/browse/DOPS-1857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [DOPS-1857] Add publish button for all libraries PRs & branches in Jenkins

.dockerignore, next.Dockerfile, next.Jenkinsfile
1. Create new Dockerfile and dockerignore for it
2. Create new jenkinsfile
Signed-off-by: Insaf Safin <safin@soramitsu.co.jp>
=> Draft deploy serve

package.json, src/components/Button/SButton/SButton.vue, src/components/Dropdown/SDropdown/SDropdown.vue, src/components/Input/SInput/SInput.vue, src/components/Tooltip/STooltip.vue, src/directives/button.ts, src/directives/index.ts, src/directives/number.ts, src/index.ts, src/types/directives.ts, src/utils/KeyValues.ts
*  SInput, SButton, SDropdown, STooltip: Fixed differences in Tabindex Types.
* Added V-Button Directive.
=> Differences in Tabindex Types Fix, V-Button Directive

config/storybook/neu-theme-variables.scss, package.json, src/styles/neumorphism/button.scss, src/styles/neumorphism/index.scss, src/styles/neumorphism/input.scss, src/styles/neumorphism/mixins.scss, src/styles/root.scss, src/styles/theme/dark.scss, src/styles/variables.scss
=> Focus Behaviour Improvements

package.json, src/styles/neumorphism/mixins.scss
* Improved Focus Outline Mixin.
=> Focus Outline Mixin Improvement

.changeset/eleven-cougars-beg.md, packages/ui/README.md, packages/ui/etc/api/ui.api.md, packages/ui/src/components/Table/STable.vue, packages/ui/src/components/Table/STableColumn.ts, packages/ui/src/components/Table/api.ts, packages/ui/src/components/Table/consts.ts, packages/ui/src/components/Table/utils.ts, packages/ui/stories/STable.stories.ts
add clickable column for details
=> WDS-107 add details table column

.changeset/breezy-jars-judge.md, .changeset/gorgeous-monkeys-lick.md, packages/ui/etc/api/ui.api.md, packages/ui/src/components/Select/SSelectButton.vue, packages/ui/src/components/Select/SSelectDropdown.vue, packages/ui/src/components/Select/SSelectInput.vue, packages/ui/src/components/Select/SSelectOption.vue, packages/ui/stories/SSelect.stories.ts
Fix some spacings in select
Fix select options font
Add size toggle to select story
=> WDS-113 select fixes

Jenkinsfile
[DOPS-2312] Create images with corepack
1. Update pipeline
Signed-off-by: name <zaporozhets@soramitsu.co.jp>
[DOPS-2312]: https://soramitsu.atlassian.net/browse/DOPS-2312
=> [DOPS: 2312] Create images with corepack

Jenkinsfile
[DOPS-2312]: use corepack
1. Added library parameter
Result:
https://jenkins.soramitsu.co.jp/job/js-ui-library/job/js-ui-library/view/change-requests/job/PR-538/lastBuild/console
Signed-off-by: Nikita Zaporozhets <zaporozhets@soramitsu.co.jp>
[DOPS-2312]: https://soramitsu.atlassian.net/browse/DOPS-2312
=> [DOPS-2312]: Use corepack

Jenkinsfile, jest.config.js, package.json
1. [Set up SonarQube coverage](https://sonar.soramitsu.co.jp/dashboard?branch=feature%2FSNE-245%2Fsonar_dojo&id=jp.co.soramitsu%3Asoramitsu-js-ui-library)
2. Connect to DefectDojo
=> SNE-245 Set up sonar,dojo

.changeset/few-lizards-raise.md, .changeset/green-ravens-occur.md, .changeset/quiet-geckos-refuse.md, .changeset/strange-elephants-sneeze.md, .changeset/wise-crabs-chew.md, packages/ui/etc/api/ui.api.md, packages/ui/src/components/DatePicker/SDatePicker.vue, packages/ui/src/components/DatePicker/SDatePickerPanelCalendars.vue, packages/ui/src/components/DatePicker/SDatePickerPanelDate.vue, packages/ui/src/components/DatePicker/SDatePickerPanelOptions.vue, packages/ui/src/components/DatePicker/SDatePickerTableDate.vue, packages/ui/src/components/DatePicker/consts.ts, packages/ui/src/components/DatePicker/types.ts, packages/ui/stories/components/DatePicker.stories.ts
Added support for null model value
Custom option now always presents in shortcuts as last one
Fixed disabled prop reactivity
Now label and menu watching model value
=> WDS-130 resettable datepicker

.changeset/curly-apricots-jump.md, packages/ui/CHANGELOG.md, packages/ui/package.json, packages/ui/src/components/Select/SSelectBase.vue
Now select search field clearing when popover closed (like in element-ui and vuetify)
=> Release next@0.13.1

.changeset/neat-boats-crash.md, packages/ui/cypress/component/Select.spec.cy.ts, packages/ui/src/components/Select/SSelectInput.vue
Now SSelect menu toggling when clicking on chevron
https://soramitsu.atlassian.net/browse/WDS-131
=> WDS-131 - Make SSelect with search close by trigger click

README.md, package.json
Now it's possible to run yarn cy from readme file.
The final variant of the command is test:ui:cy-open
=> Add cy command

.changeset/empty-numbers-eat.md, packages/ui/CHANGELOG.md, packages/ui/cypress/component/STextField.spec.cy.ts, packages/ui/etc/api/ui.api.md, packages/ui/package.json, packages/ui/src/components/Popover/SPopoverWrappedTransition.vue, packages/ui/src/components/TextField/STextField.vue, packages/ui/src/components/TextField/types.ts, packages/ui/src/components/Tooltip/STooltip.vue, packages/ui/src/components/Transitions/SCollapseTransition.vue, packages/ui/src/components/icons/index.ts, packages/ui/stories/components/TextField.stories.ts
https://soramitsu.atlassian.net/browse/WDS-134
=> Feat/WDS-134 - Add validations list to STextField

src/styles/neumorphism/index.scss
=> Feature/release 1.1.2

package.json
=> Feature/resolve conflict (#613)

package.json, src/styles/neumorphism/datepicker.scss, src/styles/neumorphism/index.scss
Release 1.1.2
Added datepicker
=> Feature/resolve conflict release (#618)
