soramitsu/soramitsu-js-ui-library

package.json
src/components/Table/STable.vue
src/components/Table/STableColumn.vue
src/stories/Table/STable.stories.ts
src/styles/table.scss

https://soramitsu.atlassian.net/browse/UNK-551

Make an area around checkbox in table inactive

---

package.json
src/components/Input/SFloatInput.vue
src/stories/SFloatInput.stories.ts

[PSS-352]: WEB UI. Input fields. Numbers are not divided by discharge.
* SFloatInput: Added Number Formatting.
[PSS-352]: https://soramitsu.atlassian.net/browse/PSS-352

PSS-352: SFloatInput - Added Number Formatting

---

package.json
src/styles/form.scss
src/styles/input.scss

Previously, the border and background of the entire component was set directly to the input element. Then, in the "Neumorphism. Button." commit the `SInput` component has been styled and the input element is now a small inner element with no borders and a background that does not cover the entire element, and the error state styling remains the same. This led to the following result:
This PR fixes this problem by applying styles specifically to the container, and not to the `<input>` itself. The hover / focus behavior is the same as before.

Fix broken `SInput` error state

---

src/components/Pagination/SPagination.vue
src/stories/SPagination.stories.ts

https://soramitsu.atlassian.net/browse/UNK-821

Of text property for pagination

---

package.json
src/components/Collapse/SCollapse/SCollapse.vue
src/stories/Collapse/SCollapse.stories.ts
src/stories/Intro/Customization.stories.ts
src/stories/SDialog.stories.ts
src/stories/SInput.stories.ts
src/styles/neumorphism/button.scss
src/styles/neumorphism/card.scss
src/styles/neumorphism/collapse.scss
src/styles/neumorphism/dialog.scss
src/styles/neumorphism/index.scss
src/styles/neumorphism/input.scss
src/styles/neumorphism/radio.scss
src/styles/neumorphism/switch.scss
src/styles/neumorphism/tabs.scss
src/styles/neumorphism/theme-variables.scss
src/styles/root.scss
src/styles/variables.scss

[PW-207]: Design Improvements
* Updated switch, inputs, button, card neu styles.
* Updated UI Lib version.
[PW-207]: https://soramitsu.atlassian.net/browse/PW-207

PW-207: Design Improvements

---

package.json
src/components/Dialog/SDialog.vue
src/styles/neumorphism/button.scss
src/styles/neumorphism/card.scss
src/styles/neumorphism/dialog.scss
src/styles/neumorphism/input.scss
src/styles/neumorphism/tabs.scss
src/styles/root.scss
src/styles/variables.scss

[PW-207]: Design Improvements
* Updated cards, dialog, tabs neumorphic shadows.
* Increased UI Lib version.
* Updated input styles.
[PW-207]: https://soramitsu.atlassian.net/browse/PW-207

PW-207: Design Improvements Updates

---

packages/theme/tsconfig.json
tsconfig.json

More context here: https://github.com/johnsoncodehk/volar/issues/1232

Remove `declaration: true` to avoid Volar "Props" issue

---

.changeset/tall-walls-boil.md
packages/ui/cypress/component/STextField.spec.cy.ts
packages/ui/src/components/TextField/STextField.vue

Before there was an issue when extra attribute is passed:
Also vue documentation says that `attrs` are not reactive. But it is a mystery why it was... Anyway, not attrs are used in the correct way (I hope).

Fix extra attributes passing in `STextField`

---

.changeset/eleven-donuts-sin.md
.changeset/nine-vans-dress.md
.changeset/real-radios-repair.md
.changeset/sixty-pants-dance.md
.changeset/sweet-baboons-brush.md
.changeset/wild-timers-act.md
packages/ui/cypress/component/Select.spec.cy.ts
packages/ui/etc/api/ui.api.md
packages/ui/src/components/Popover/SPopover.ts
packages/ui/src/components/Select/SDropdown.vue
packages/ui/src/components/Select/SSelect.vue
packages/ui/src/components/Select/SSelectBase.vue
packages/ui/src/components/Select/SSelectButton.vue
packages/ui/src/components/Select/SSelectChevron.scss
packages/ui/src/components/Select/SSelectChevron.ts
packages/ui/src/components/Select/SSelectChip.vue
packages/ui/src/components/Select/SSelectDropdown.vue
packages/ui/src/components/Select/SSelectInput.vue
packages/ui/src/components/Select/SSelectOption.vue
packages/ui/src/components/Select/api.ts
packages/ui/src/components/Select/sizes-mixin.scss
packages/ui/src/components/Select/use-model.spec.ts
packages/ui/src/components/Select/use-model.ts
packages/ui/src/components/TextField/STextField.vue
packages/ui/stories/SSelect.stories.ts

(after https://github.com/soramitsu/soramitsu-js-ui-library/pull/497)
Text field:
- add `prefix` slot - inline elements before input and `filledState` prop to use filled state when prefix presents
- fix input font
Select:
- add empty slot for menu
- add `triggerSearch` prop to enable search input in select input
- add `remoteSearch` prop that disables default search behaviour

WDS-125 async select search

---

.changeset/famous-sheep-flow.md
packages/ui/src/components/Checkbox/SCheckboxSolo.vue
packages/ui/src/components/Radio/SRadio.vue
packages/ui/src/components/Radio/SRadioBody.scss
packages/ui/src/components/Radio/SRadioBody.ts

Checkbox and radio:
- refactor: moved common styles to common component
- added different paddings for different sizes and types
- removed hover background that was not in design

WDS-119 fix styles for radio and checkbox components

---

.changeset/wise-trees-applaud.md
packages/ui/src/components/Table/use-table-heights.ts

[fix] #517: refactor heights watcher

---

.changeset/quiet-badgers-beg.md
.changeset/quiet-ghosts-hug.md
.changeset/spicy-rivers-run.md
.changeset/tricky-seas-knock.md
.eslintrc.js
packages/ui/src/components/Alert/SAlert.vue
packages/ui/src/components/Modal/SModal.vue
packages/ui/src/components/Modal/SModalCard.vue
packages/ui/src/components/Notifications/SNotificationBody.vue
packages/ui/src/components/Notifications/SUseNotification.ts
packages/ui/src/components/Switch/SSwitch.vue
packages/ui/src/components/TextField/STextField.vue
packages/ui/src/composables/element-id-fallback.ts

[refactor] #513: enable ESLint a11y rules back

---

next.Jenkinsfile

Change Node's version that is used in branch "next" from 14 to 16
1. node:16-ubuntu-cypress image added
Signed-off-by: Naghme Mohammadifar <mohammadi.far@soramitsu.co.jp>

update node v16

---

.changeset/nervous-monkeys-bow.md
.changeset/serious-dragons-clap.md
.changeset/tough-hounds-help.md
packages/ui/etc/api/ui.api.md
packages/ui/src/components/DatePicker/SDatePicker.vue
packages/ui/src/components/DatePicker/SDatePickerPanelTime.vue
packages/ui/src/components/DatePicker/SDatePickerTableDate.vue
packages/ui/src/components/DatePicker/api.ts
packages/ui/src/components/DatePicker/date-util.ts
packages/ui/src/components/DatePicker/types.ts

Fixed no watch value prop
Added the ability to show picker without shortcuts
Make time panel also filtered by `dateFilter`, `min`, `max` prop

WDS-128 time disable, fix vmodel watch, no shortcuts

---

package.json
src/styles/collapse.scss

Hello!
Looks like CSS attributes were mistakenly applied to another element.
The arrow was especially noticeable off-center at 125% and 175% zoom.
Showcase:
https://user-images.githubusercontent.com/2076748/227840869-03d82806-7957-41f6-934e-9e77be905529.mp4

Fix center state for arrow in collapse fix

---

.changeset/brave-plums-count.md
.changeset/sweet-knives-obey.md
packages/ui/src/components/Table/STable.vue
packages/ui/src/components/Table/use-flex-columns-widths.ts

This pr created in order to remove space between column and border line as in the following picture.
Also I edited STable styles by applying overflow-y:auto to the whole table.

Fix - Remove column width rounding

---

.changeset/bright-boats-wash.md
packages/ui/src/components/Alert/SAlert.vue

Motivation:
Current SAlert implementation has warning because of the status icon computation. 
Now, we will use it's implementation instead of itself.
Instead of using eagerComputed
```
const StatusIcon = eagerComputed(() => STATUS_ICONS_MAP[props.status])
```
We will use native Vue watshSyncEffect
```
const StatusIcon = shallowRef<Component>()
watchSyncEffect(() => {
StatusIcon.value = STATUS_ICONS_MAP[props.status]
})
```
Warning resolved✅
By the way, in Vue 3.4+ native computed was greatly improved and later we can replace every eagerComputed usage with it.

Fix - Edit SAlert icon computation

---

.changeset/kind-experts-attend.md
.changeset/purple-bananas-flow.md
packages/ui/CHANGELOG.md
packages/ui/package.json
packages/ui/src/components/Modal/SModalCard.vue
packages/ui/stories/components/Modal.stories.ts

Without following styles div containing slot in s-modal-card component won't scroll so we have to add these styles every time.
```
& > div:last-child {
display: flex;
flex-grow: 1;
flex-direction: column;
min-height: 0;
}
```
I've also added s-modal-card__content class so it will be easier to apply styles to that div.

Fix - Add classes for s-modal div

---

.changeset/wet-horses-hope.md
packages/ui/CHANGELOG.md
packages/ui/etc/api/ui.api.md
packages/ui/package.json
packages/ui/src/components/Select/SDropdown.vue
packages/ui/src/components/Select/SSelect.vue
packages/ui/src/components/Select/SSelectDropdown.vue
packages/ui/stories/components/select/common.ts

#574 
Also I applied sameWidthPopper prop because without it SDropdown loading state would look like this
These commits aren't really organized because I had an issue with updating api.md file. Now it's resolved :)

Feature - Add prop to limit s dropdown height

---

.changeset/wise-pens-move.md
packages/ui/CHANGELOG.md
packages/ui/etc/api/ui.api.md
packages/ui/package.json
packages/ui/src/components/Table/STable.vue
packages/ui/src/components/Table/STableCard.vue
packages/ui/src/components/Table/types.ts
packages/ui/src/components/Table/use-column-expand.ts
packages/ui/src/components/Table/use-column-sort.ts
packages/ui/src/components/Table/use-row-select.ts

#545 
Now value will be the same type as provided data instead of TableRow. Example with one of the events:
For future : somehow we have to provide generics for `formatter` property in STableColumn component.

Fix - Add generics to table data

---

.changeset/brown-elephants-hunt.md
packages/ui/CHANGELOG.md
packages/ui/package.json
packages/ui/src/components/Select/SDropdown.vue

The aim of this pr is to fix such display
But also prop should apply whenever loading is true to avoid the following display
https://soramitsu.atlassian.net/browse/CBDC-1941

Fix/CBDC-1941 - Pagination page size dropdown
